#!/bin/bash
# Script to remove headers

# Number of lines to remove
n=26

# Files from where it should be removed. Entries can
# be inhabilitated by commenting them with '#'

files=(
mod_small_values.t
advance.t
amr_coarsen_refine.t
amr_fix_conserve.t
amr_gc_comm.t
amr_ghostcells.t
amrgrid.t
amrini.t
amr_neighbors.t
amr_solution_node.t
amrvacdef.t
amrvacsettings.t
amrvac.t
boundary_conditions.t
coarsen.t
comm_lib.t
connectivity.t
errest.t
forest.t
initialize_vars.t
load_balance.t
m_octree_mg_2d.t
m_octree_mg_3d.t
mod_connectivity.t
mod_fix_conserve.t
mod_forest.t
mod_gc_comm.t
mod_indices.t
mod_limiter.t
mod_multigrid_coupling.t
mod_physicaldata.t
#mod_watchdog.t
mp5.t
ppm.t
weno.t
refine.t
selectgrids.t
set_B0.t
setdt.t
finite_volume.t
finite_difference.t
ID_reader/mod_xns.t
ID_reader/mod_c2b.t
ID_reader/mod_c2b_cart3d.t
modules/mod_timing.t
modules/mod_rtsafe2D.t
modules/mod_random.t
modules/mod_particles.t
modules/mod_oneblock.t
modules/mod_odeint.t
modules/mod_ngmres.t
modules/mod_lu.t
modules/mod_interpolate.t
#modules/mod_gridvars.t
modules/mod_constants.t
#modules/makefile
geometry/mod_transform.t
geometry/mod_metric.t
geometry/mod_metric_aux.t
geometry/mod_coord_sstest.t
geometry/mod_coord_ss.t
geometry/mod_coord_sp.t
geometry/mod_coord_rzy.t
geometry/mod_coord_rz.t
geometry/mod_coord_rzks.t
geometry/mod_coord_rns.t
geometry/mod_coord_num.t
geometry/mod_coord_mks.t
geometry/mod_coord_mksnorm.t
geometry/mod_coord_ks.t
geometry/mod_coord_cylks.t
geometry/mod_coord_cmks.t
geometry/mod_coord_cks.t
geometry/mod_coord_ckn.t
geometry/mod_coord_cart.t
geometry/mod_coord_cartfunky.t
geometry/mod_coord_brane.t
geometry/mod_coord_bl.t
geometry/mod_bl.t
geometry/makefile
geometry/geometry.t
amrvacphys/srhdhllc.t
amrvacphys/rhdroe.t
amrvacphys/correctauxsrhd.t
amrvacnul/usrflags.t
amrvacnul/userspecialconvert.t
amrvacnul/specialsource.t
amrvacnul/speciallog.t
amrvacnul/specialini.t
amrvacnul/specialimpl.t
amrvacnul/specialbound.t
amrvacnul/roe.t
amrvacnul/hllc.t
amrvacnul/getdt.t
amrvacnul/getaux.t
amrvacnul/correctaux_usr.t
amrvacnul/addsource.t
amrvacmodules/viscosity.t
amrvacmodules/raytracing.t
amrvacmodules/radloss.t
amrvacmodules/pointgrav.t
amrvacmodules/pfss.t
amrvacmodules/magnetofriction.t
amrvacmodules/integrate_particles.t
amrvacmodules/init_particles.t
amrvacmodules/heatconduct.t
amrvacmodules/handle_particles.t
amrvacmodules/gravity.t
amrvacmodules/fff.t
amrvacmodules/epsinf.t
amrvacmodules/cooling.t
amrvacmodules/coolingpar.t
amrvacmodules/convertsym23.t
amrvacio/slice.t
amrvacio/mod_shell.t
amrvacio/makefile
amrvacio/kracken.t
amrvacio/convert.t
amrvacio/collapse.t
amrvacio/analysis.t
amrvacio/amrio.t
eos_modules/mod_eos.t
eos_modules/mod_eos_idealgas.t
eos_modules/mod_eos_polytrope.t
eos_modules/mod_eos_tabulated.t
eos_modules/mod_eos_interpolation.t
eos_modules/mod_eos_tabulated_parameters.t
eos_modules/mod_eos_readtable.t
imhd/amrvacpar.t
imhd/amrvacphys.t
imhd/correctaux.t
imhd/divb.t
imhd/fct.t
imhd/mod_amr_fct.t
imhd/mod_full_gr_source.t
imhd/mod_imhd_con2prim.t
imhd/mod_physaux.t
imhd/mod_imhd_intermediate.t
geometry/cfc/mod_cfc.t
geometry/cfc/mod_cfc_parameters.t
geometry/cfc/mod_cfc_alp.t
geometry/cfc/mod_cfc_beta.t
geometry/cfc/mod_cfc_psi.t
mod_variables.t
)

for name in "${files[@]}"
do
    sed -i -e 1,$((n))d $name
done


