#undefine C2PREL
#define DY_SP
#define HARDBC
#define TABEOS
#define M1
#define M1_RATES
#define M1_RECONSTRUCT
#undefine M1_EXPLICIT
#define VAR1
#define M1VARS
#undefine M1_CONSVAR
#undefine M1_CONSVAR2
#undefine M1_CONSVAR1
#undefine M1_RADVAR
#undefine FOO
#undefine FOO5

#undefine DEBUG_BACKREACT
#undefine NAN_CHECK
#undefine DEBUGMEE
#undefine DEBUGMEE1
#undefine DEBUGMEEC2P
#undefine DEBUGMEEFVOL
#undefine DEBUGMEEFVOL2
#undefine DEBUGMEEM1WAVE
#undefine DEBUGMEEM1FLUX
#undefine DEBUGMEEM1CORRFLUX
#undefine DEBUGMEEM1GEO
#undefine DEBUGMEEM1GEO2
#undefine DEBUGMEEM1COLL
#undefine METH


#undefine GW_BR
#dunefine FROMCARPET
#undefine EPSINF
#undefine GLM
#undefine NORMINIT
#undefine HDF5
#undefine FCT
#undefine SFC_ON_BASE
#undefine EXTRAFLAGS
#undefine ENTROPY
#undefine ELECTRONS
#undefine STAGGERED
#undefine HALL
#undefine UCONVERT
#undefine SAVENOW
#undefine TRANSFORMW
#undefine RAY
#undefine BIGENDIAN
#undefine FOURTHORDER
#undefine TCRKL2
#undefine TCPERPENDICULAR
#undefine SPECIALTOLERANCE
#undefine MAGNETOFRICTION
#undefine PARTICLES
#undefine BOUNDARYDRIVER
