name: "grace"
amr: {
  npoints_block_x: 6,
  npoints_block_y: 6,
  npoints_block_z: 6,
  n_ghostzones: 1,
  initial_refinement_level: 0
}
eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",

  ye_atmosphere: 0,
  temp_atmosphere: 0,
  rho_atmosphere: 1.e-14,
  eps_maximum: 1.e+05,
  gamma_th: 1.8,

  atm_is_beta_eq: true,
  extend_table_high: false,

  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [ 2. ],
    rhos:   [ ],
    kappa_0: 1.685819e+02
  }
}