name: "grace"
amr: {
  npoints_block_x: 128,
  npoints_block_y: 128,
  npoints_block_z: 128,
  xmin: -128.0,
  xmax: 128.0,
  ymin: -128.0,
  ymax: 128.0,
  zmin: -64.0,
  zmax: 64.0,

  n_ghostzones: 4,
  initial_refinement_level: 2,
  refinement_criterion: "simple_threshold",
  refinement_criterion_CTORE: 2.,
  refinement_criterion_CTODE: 1.,
  refinement_criterion_var: "U",
  max_refinement_level: 7,
  regrid_every: -1,
  regrid_at_postinitial: false
}
IO: {
  volume_output_cell_variables: ["rho","press","eps","vel[0]", "Bvec[0]","Bdiv"],
  volume_output_base_directory: "output_volume",
  volume_output_every: -1,
  plane_surface_output_cell_variables: ["alp","rho","press","eps","vel[0]", "Bvec[0]","Bdiv","entropy","b2","c2p_err"],
  plane_surface_output_every: 100,
  sphere_surface_output_every: -1,
  do_initial_output: true,
  info_output_every: 2,
  info_output_max_reductions: ["rho", "press", "Bdiv","b2"],
  info_output_min_reductions: [], 
  info_output_norm2_reductions: ["Bdiv","c2p_err"], 
  scalar_output_every: 50,
  scalar_output_minmax: ["rho","press","eps","Bdiv"],
  scalar_output_norm2: ["Bdiv"],
  scalar_output_integral: [],
  output_use_hdf5: true, 
  hdf5_compression_level: 0,
  hdf5_chunk_size: 131072,
  output_extra_quantities: true
}
system: {
  console_log_level: "info",
  file_log_level: "info",
  flush_logs_based_on_severity: false,
  flush_level: "trace",
  n_device_streams: 4
}
evolution: {
  time_stepper: "rk2",
  cfl_factor: 0.2,
  final_time: 2000.0
}
grmhd: {
  id_type: "fmtorus",
  lapse_excision: 0.8,
  Avec_ID: {
    kind: "current_loop",
    cutoff_var: "rho",
    cutoff_fact: 0.2,
    A_phi: 1.0,
    A_n: 1.0
  },
  fmtorus: {
    a_BH: 0.9375,
    rho_min: 1.0e-5,
    lapse_min: 0.8,
    press_min: 0.333e-7,
    r_in: 6,
    r_at_max_density: 12,
    gamma: 1.33333333333,
    max_inverse_beta: 100,
    perturbation_amplitude: 0.02,
    rho_power: -1.5,
    press_power: -2.5,
    rho_max: 1.0
  },
  B_field_from_Avec: true,
  excision: {
    excision_criterion: "radius",
    excision_radius: 1.0,
    rho_excision: 1e-8,
    temp_excision: 0.3333e-2,
    excision_lapse: 0.2
  },
  atmosphere: {
    ye_fl: 0,
    temp_fl:  0.3333e-2,
    rho_fl: 1.e-5,
    rho_scaling: -1.5,
    temp_scaling: -1
  }
}

eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",

  eps_maximum: 1.e+05,
  gamma_th: 1.33333333333,

  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [2.],
    rhos:   [],
    kappa_0: 0.
  }
}

profiling: {
  do_gpu_profiling: false
}

checkpoints: {
  checkpoint_at_termination: false,
  checkpoint_dir: "./checkpoints"
}