name: "grace"
amr: {
  npoints_block_x: 16,
  npoints_block_y: 16,
  npoints_block_z: 16,
  xmin: -3.0,
  xmax: 3.0,
  ymin: -6.0,
  ymax: 6.0,
  zmin: -3.0,
  zmax: 3.0,
  periodic_x: true,
  periodic_y: true,
  periodic_z: true,
  n_ghostzones: 2,
  initial_refinement_level: 3,
  refinement_criterion: "gradient",
  refinement_criterion_CTORE: 0.1,
  refinement_criterion_CTODE: 0.025,
  refinement_criterion_var: "press",
  refinement_criterion_var_is_aux: true,
  max_refinement_level: 7,
  regrid_every: 50,
  regrid_at_postinitial: false
}
IO: {
  volume_output_cell_variables: ["rho","press"],
  volume_output_base_directory: "output_volume_hllc_blastwave",
  volume_output_every: 200,
  plane_surface_output_cell_variables: [],
  plane_surface_output_every: -1,
  sphere_surface_output_every: -1,
  info_output_every: 20,
  info_output_max_reductions: ["eps","rho","press"],
  #["eps","rho","stilde[0]", "stilde[1]","stilde[2]","dens","press"],
  info_output_min_reductions: ["eps","rho","press"],
  #["eps","rho","stilde[0]", "stilde[1]","stilde[2]","dens","press"], 
  scalar_output_every: 50,
  scalar_output_minmax: ["rho","press","eps"],
  scalar_output_norm2: [],
  scalar_output_integral: [],
  output_use_hdf5: true, 
  hdf5_compression_level: 6,
  hdf5_chunk_size: 8192
}
system: {
  console_log_level: "info",
  file_log_level: "trace",
  flush_logs_based_on_severity: false,
  flush_level: "trace"
}
evolution: {
  time_stepper: "rk2",
  cfl_factor: 0.4,
  final_time: 25,
  #timestep: 0.00025,
  #timestep_selection_mode: "manual"
}
grmhd: {
  id_type: "blastwave",
  blastwave_over_pressure_factor: 25,
}

eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",

  ye_atmosphere: 0,
  temp_atmosphere: 0,
  rho_atmosphere: 1.e-14,
  eps_maximum: 1.e+05,
  gamma_th: 1.3333,

  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [2.],
    rhos:   [],
    kappa_0: 0.
  }
}

profiling: {
  do_gpu_profiling: false
}