name: "grace"
# NB you need frozen BC for this test! 
amr: {
  npoints_block_x: 32,
  npoints_block_y: 32,
  npoints_block_z: 32,
  xmin: 0.,
  xmax: 5.,
  ymin: 0.,
  ymax: 0.5,
  zmin: -5.,
  zmax:  5.,
  reflection_symmetries: {
    x: false,
    y: true, 
    z: false
  },
  n_ghostzones: 4,
  initial_refinement_level: 0,
  regrid_every: -1,
  regrid_at_postinitial: false
}

IO: {
  plane_surface_output_cell_variables: ["Erad", "Frad[0]"],
  plane_surface_output_every: 10,
  info_output_every: 2,
  info_output_max_reductions: ["Erad","rho"],
  info_output_min_reductions: ["Erad","rho"],
  output_use_hdf5: true, 
  hdf5_compression_level: 0,
  hdf5_chunk_size: 512,

  output_plane_y_origin_1: 0.0078125,
}

system: {
  console_log_level: "info",
  file_log_level: "info",
  flush_logs_based_on_severity: false,
  n_device_streams: 4
}

coordinate_system: {
  is_kerr_schild: true,
  bh_spin: 0
}

evolution: {
  time_stepper: "rk3",
  cfl_factor: 0.2,
  final_time: 10
}

m1: {
  id_type: "curved_beam"
}

profiling: {
  do_gpu_profiling: false
}

checkpoints: {
  checkpoint_at_termination: false,
}