name: "grace"
amr: {
  npoints_block_x: 32,
  npoints_block_y: 32,
  npoints_block_z: 32,
  xmin: -10.,
  xmax: 10.,
  ymin: -10.,
  ymax: 10.,
  zmin: -10.,
  zmax: 10.,
  n_ghostzones: 4,
  initial_refinement_level: 3,
  regrid_every: -1,
  regrid_at_postinitial: false
}

IO: {
  plane_surface_output_cell_variables: ["Erad", "Frad[0]"],
  plane_surface_output_every: 10,
  info_output_every: 2,
  info_output_max_reductions: ["Erad","rho"],
  info_output_min_reductions: ["Erad","rho"],
  output_use_hdf5: true, 
  hdf5_compression_level: 0,
  hdf5_chunk_size: 512
}

system: {
  console_log_level: "info",
  file_log_level: "info",
  flush_logs_based_on_severity: false,
  n_device_streams: 4
}

evolution: {
  time_stepper: "imex222",
  cfl_factor: 0.2,
  final_time: 10.,
  #termination_condition: "iteration",
  #final_iteration: 15
}

m1: {
  id_type: "emitting_sphere",
  emitting_sphere_test: {
    kappa_eta: 10.0
  }
}

profiling: {
  do_gpu_profiling: false
}

checkpoints: {
  checkpoint_at_termination: false,
}