name: "grace"
amr: {
  npoints_block_x: 32,
  npoints_block_y: 32,
  npoints_block_z: 32,
  xmin: -5,
  xmax: 5,
  ymin: -1.25,
  ymax: 1.25,
  zmin: -1.25,
  zmax: 1.25,
  periodic_x: true,
  periodic_y: true,
  periodic_z: true,
  n_ghostzones: 4,
  initial_refinement_level: 2,
  regrid_every: -1,
  regrid_at_postinitial: false
}

IO: {
  plane_surface_output_cell_variables: ["Erad", "Frad[0]"],
  plane_surface_output_every: 10,
  info_output_every: 2,
  info_output_max_reductions: ["Erad","vel[0]"],
  info_output_min_reductions: ["Erad","vel[0]"],
  output_use_hdf5: true, 
  hdf5_compression_level: 0,
  hdf5_chunk_size: 512
}

system: {
  console_log_level: "info",
  file_log_level: "info",
  flush_logs_based_on_severity: false,
  n_device_streams: 4
}

evolution: {
  time_stepper: "imex222",
  cfl_factor: 0.2,
  final_time: 4,
  #termination_condition: "iteration",
  #final_iteration: 15
}

m1: {
  id_type: "scattering",
  scattering_test: {
    k_s: 1e03, 
    t_0: 1,
    is_static_background: false
  }
}

grmhd: {
  id_type: "minkowski_vacuum",
  vacuum: {
    rho_floor: 1e-15,
    press_floor: 1e-15,
    velocity_x: 0.5,
    velocity_y: 0.,
    velocity_z: 0.
  }
}

profiling: {
  do_gpu_profiling: false
}

checkpoints: {
  checkpoint_at_termination: false,
}