name: "grace"
amr: {
  npoints_block_x: 16,
  npoints_block_y: 16,
  npoints_block_z: 16,
  xmin: -3.1415,
  xmax: 3.1415,
  ymin: -3.1415,
  ymax: 3.1415,
  zmin: -0.31415,
  zmax: 0.31415,
  periodic_x: true,
  periodic_y: true,
  periodic_z: true,
  n_ghostzones: 4,
  initial_refinement_level: 0,
  refinement_criterion: "simple_threshold",
  refinement_criterion_CTORE: 2.,
  refinement_criterion_CTODE: 1.,
  refinement_criterion_var: "U",
  max_refinement_level: 7,
  regrid_every: -1,
  regrid_at_postinitial: false
}
IO: {
  volume_output_cell_variables: ["rho","press","eps","vel[0]", "Bvec[0]","Bdiv"],
  volume_output_base_directory: "output_volume",
  volume_output_every: 930,
  plane_surface_output_cell_variables: ["rho","press","eps","vel[0]", "Bvec[0]"],
  plane_surface_output_every: -1,
  sphere_surface_output_every: -1,
  info_output_every: 2,
  info_output_max_reductions: ["rho", "press", "Bvec[1]", "Bdiv"],
  info_output_min_reductions: ["rho", "press", "Bvec[1]"], 
  scalar_output_every: 50,
  scalar_output_minmax: ["rho","press","eps","Bdiv"],
  scalar_output_norm2: ["Bdiv"],
  scalar_output_integral: [],
  output_use_hdf5: true, 
  hdf5_compression_level: 6,
  hdf5_chunk_size: 128,
  output_extra_quantities: true
}
system: {
  console_log_level: "info",
  file_log_level: "trace",
  flush_logs_based_on_severity: true,
  flush_level: "trace",
  n_device_streams: 4
}
evolution: {
  time_stepper: "rk3",
  cfl_factor: 0.25,
  final_time: 10.5,
  #termination_condition: "iteration",
  #final_iteration: 15
}
grmhd: {
  id_type: "orszag_tang_vortex"
}

eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",

  ye_atmosphere: 0,
  temp_atmosphere: 0,
  rho_atmosphere: 1.e-14,
  eps_maximum: 1.e+05,
  gamma_th: 1.333333,

  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [2.],
    rhos:   [],
    kappa_0: 0.
  }
}

profiling: {
  do_gpu_profiling: false
}

checkpoints: {
  checkpoint_at_termination: false,
}