name: "grace"
amr: {
  npoints_block_x: 16,
  npoints_block_y: 16,
  npoints_block_z: 16,

  xmin: -32.0,
  xmax: 32.0,
  ymin: -32.0,
  ymax: 32.0,
  zmin: 0.0,
  zmax: 32.0,

  reflection_symmetries: {
  			 x: false,
  			 y: false,
  			 z: true
  }, 

  n_ghostzones: 4,
  initial_refinement_level: 2,
  
  max_refinement_level: 7,
  regrid_every: -1,
  regrid_at_postinitial: false,

  n_fmr_boxes: 4,
  fmr_box_0: {
    target_level_delta: 1,
    x_min: -16,
    x_max: 16,
    y_min: -16,
    y_max: 16,
    z_min: 0,
    z_max: 16
  },
  fmr_box_1: {
    target_level_delta: 2,
    x_min: -8,
    x_max: 8,
    y_min: -8,
    y_max: 8,
    z_min: 0,
    z_max: 8
  },
  fmr_box_2: {
    target_level_delta: 3,
    x_min: -4,
    x_max: 4,
    y_min: -4,
    y_max: 4,
    z_min: 0,
    z_max: 4
  },
  fmr_box_3: {
    target_level_delta: 4,
    x_min: -2,
    x_max: 2,
    y_min: -2,
    y_max: 2,
    z_min: 0,
    z_max: 2
  }
}

IO: {
  plane_surface_output_cell_variables: ["z4c_H", "z4c_M[0]", "beta[0]", "z4c_Khat", "gamma_tilde[0,0]", "gamma_tilde[0,1]", "gamma_tilde[0,2]", "gamma_tilde[1,1]", "gamma_tilde[1,2]", "gamma_tilde[2,2]", "z4c_theta", "conf_fact", "z4c_Gamma[0]","A_tilde[0,0]","A_tilde[0,1]","A_tilde[0,2]", "A_tilde[1,1]", "A_tilde[1,2]", "A_tilde[2,2]", "alp"],
  plane_surface_output_every: 100,

  info_output_every: 2,
  info_output_max_reductions: ["conf_fact", "z4c_Gamma[0]"],
  info_output_min_reductions: ["alp","conf_fact"],
  info_output_norm2_reductions: ["z4c_H"],

  scalar_output_every: 2,
  scalar_output_minmax: ["z4c_H","conf_fact","alp"],
  scalar_output_norm2: ["z4c_H"],
  scalar_output_integral: [],

  output_use_hdf5: true,
  hdf5_compression_level: 0,
  hdf5_chunk_size: 8192,
  output_extra_quantities: true,

  output_plane_z_origin_0: 1e-5,
}
system: {
  console_log_level: "info",
  file_log_level: "info",
  flush_logs_based_on_severity: false,
  flush_level: "trace",
  n_device_streams: 4
}
evolution: {
  time_stepper: "rk3",
  cfl_factor: 0.1,
  final_time: 4000
}

grmhd: {
  id_type: "two_punctures",
  two_punctures: {
    par_b: 1e-4,

    target_M_plus: 1.0,
    par_P_plus_x: 0.0,
    par_P_plus_y: 0.0,
    par_P_plus_z: 0.0,
    par_S_plus_x: 0.0,
    par_S_plus_y: 0.0,
    par_S_plus_z: 0.0,

    target_M_minus: 0.0,
    par_P_minus_x: 0.0,
    par_P_minus_y: 0.0,
    par_P_minus_z: 0.0,
    par_S_minus_x: 0.0,
    par_S_minus_y: 0.0,
    par_S_minus_z: 0.0,

    npoints_A: 30,
    npoints_B: 30,
    npoints_phi: 16,

    TP_epsilon: 1.e-8
  }
}

z4c: {
  kappa_1: 0.02,
  kappa_2: 0.0,
  eta: 1.,
  eps_diss: 0.25,
  is_vacuum: true,
  eta_damp_radius: 16,
  theta_damp_radius: -1,
  kappa_damp_radius: 16,
  alp_excision: -1.0
}

