name: "grace"
amr: {
  npoints_block_x: 16,
  npoints_block_y: 16,
  npoints_block_z: 16,
  xmin: -50,
  xmax: 50,
  ymin: -50,
  ymax: 50,
  zmin: -50,
  zmax: 50,
  n_ghostzones: 2,
  initial_refinement_level: 5,
  refinement_criterion: "simple_threshold",
  refinement_criterion_CTORE: 1e-05,
  refinement_criterion_CTODE: 1e-8,
  refinement_criterion_var  : "rho",
  refinement_criterion_var_is_aux: true,
  max_refinement_level: 10,
  regrid_every: -1,
  regrid_at_postinitial: true,
  postinitial_regrid_depth: 2
}
IO: {
  volume_output_cell_variables: ["rho","press","eps","vel[0]", "zvec[0]", "gamma[0,0]", "alp", "beta[0]"],
  volume_output_base_directory: "output_volume",
  volume_output_every: 100,
  plane_surface_output_cell_variables: [],
  plane_surface_output_every: -1,
  sphere_surface_output_every: -1,
  info_output_every: 20,
  info_output_max_reductions: ["alp", "eps","rho","press"],
  #["eps","rho","stilde[0]", "stilde[1]","stilde[2]","dens","press"],
  info_output_min_reductions: ["alp", "eps","rho","press"],
  #["eps","rho","stilde[0]", "stilde[1]","stilde[2]","dens","press"],
  scalar_output_every: 2,
  scalar_output_minmax: ["rho","press","eps"],
  scalar_output_norm2: [],
  scalar_output_integral: [],
  output_use_hdf5: true,
  hdf5_compression_level: 6,
  hdf5_chunk_size: 8192,
  output_extra_quantities: true
}
system: {
  console_log_level: "info",
  file_log_level: "trace",
  flush_logs_based_on_severity: true,
  flush_level: "trace"
}
evolution: {
  time_stepper: "rk2",
  cfl_factor: 0.2,
  final_time: 2000,
  reset_id_after_regrid: true
  #timestep: 0.00025,
  #timestep_selection_mode: "manual"
}
grmhd: {
  id_type: "TOV",
  TOV_central_density: 1.e-03
}

eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",

  ye_atmosphere: 0,
  temp_atmosphere: 0,
  rho_atmosphere: 1.e-10,
  eps_maximum: 1.e+05,
  gamma_th: 0,

  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [2.],
    rhos:   [],
    kappa_0: 100.
  }
}