name: "grace"
amr: {
  npoints_block_x: 64,
  npoints_block_y: 64,
  npoints_block_z: 64,
  xmin: -64,
  xmax: 64,
  ymin: -64,
  ymax: 64,
  zmin: -64,
  zmax: 64,
  n_ghostzones: 4,
  initial_refinement_level: 3,
  regrid_every: -1
}
IO: {
  volume_output_cell_variables: ["rho","press","eps","vel[0]", "alp", "beta[0]"],
  volume_output_base_directory: "output_volume",
  volume_output_every: -1,

  plane_surface_output_cell_variables: [],
  plane_surface_output_every: -1,

  sphere_surface_output_every: -1,

  info_output_every: 20,
  info_output_max_reductions: ["alp", "eps","rho","press"],
  info_output_min_reductions: ["alp"],

  scalar_output_every: 2,
  scalar_output_minmax: ["rho","press","eps","alp"],
  scalar_output_norm2: [],
  scalar_output_integral: [],

  output_use_hdf5: true,
  hdf5_compression_level: 0,
  hdf5_chunk_size: 8192,
  output_extra_quantities: true
}
system: {
  console_log_level: "info",
  file_log_level: "info",
  flush_logs_based_on_severity: false,
  flush_level: "trace",
  n_device_streams: 4
}
evolution: {
  time_stepper: "rk3",
  cfl_factor: 0.2,
  final_time: 2000
  #timestep: 0.00025,
  #timestep_selection_mode: "manual"
}
grmhd: {
  id_type: "TOV",
  TOV_central_density: 1.28e-03,

  Avec_ID: {
    kind: "current_loop",
    cutoff_var: "press",
    cutoff_fact: 0.02,
    A_phi: 0,
    A_n: 2.0
  },
  B_field_from_Avec: true,

  atmosphere: {
    ye_fl: 0,
    temp_fl:  0.0,
    rho_fl: 1.e-14,
    rho_scaling:  9,
    temp_scaling: 9,
    max_lorentz: 50,
    max_sigma: 100,
    c2p_tolerance: 1e-10,
    beta_fallback: 1e-2,
    use_c2p_entropy_backup: true
  },

  excision: {
    excision_criterion: "lapse",
    excision_lapse: 0.05,
    excision_radius: 1.0,
    rho_excision: 1e-8,
    temp_excision: 0.3333e-2
  }

}

z4c: {
  kappa_1: 0.02,
  kappa_2: 0.1,
  eta: 1.00,
  mu_S: 1.0,
  mu_L: 1.0,
  epsdiss: 0.0
}

eos: {
  eos_type: "hybrid",
  cold_eos_type: "piecewise_polytrope",

  ye_atmosphere: 0,
  temp_atmosphere: 0,
  rho_atmosphere: 1.e-14,
  eps_maximum: 1.e+05,
  gamma_th: 1.8,

  piecewise_polytrope: {
    n_pieces: 1,
    gammas: [2.],
    rhos:   [],
    kappa_0: 100.
  }
}
